  version: '3.9'
  services:
    rabbitmq:
      container_name: rabbitmq
      restart: always
      image: rabbitmq:management-alpine
      environment:
        - RABBITMQ_DEFAULT_USER=rabbitmq
        - RABBITMQ_DEFAULT_PASS=rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
