version: "3.9"
services:
  web:
    image: nginx:alpine
    container_name: web
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
