version: '3.1'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./datos:/var/lib/postgresql/data
